import { liga } from '@/lib/liga';
export const metadata = { title: 'Regras' };
export default function Pagina() { return <article className="regulamento">
  <div className="titulo-pagina"><div><h1>O combinado é o combinado.</h1><p>Condições da primeira temporada · Site com dados demonstrativos</p></div></div>
  <p className="intro">Estas são as condições de participação do Várzeão no modo Clubs, 11 contra 11. A classificação, os clubes e as súmulas exibidos no site são de uma temporada exemplo.</p>
  <section><h2>1. Início e calendário</h2><p>A primeira temporada começa quando as equipes estiverem fechadas. Serão duas rodadas durante a semana, com dias e horários divulgados antes do início. Haverá também copas com premiação ao longo da temporada.</p><p>A demonstração apresenta dez clubes em nove rodadas de turno único. O calendário oficial será publicado pela organização.</p><ul><li>Vitória: 3 pontos.</li><li>Empate: 1 ponto para cada clube.</li><li>Derrota: nenhum ponto.</li></ul><p>A tabela demonstrativa desempata por saldo de gols, gols pró e ordem alfabética. Os critérios definitivos serão publicados antes da competição.</p></section>
  <section><h2>2. Mensalidade e responsabilidade do capitão</h2><p>A mensalidade é de R$ {liga.mensalidadeTime} por time. O capitão recolhe as contribuições do elenco e realiza o pagamento à plataforma.</p><p>Dividindo igualmente, são R$ 20 por pessoa em um elenco de 15 jogadores ou R$ 25 em um elenco de 12. O painel demonstra o acompanhamento das contribuições individuais. Jogadores com mensalidade pendente aparecem impedidos de ser escalados.</p><p>Informações de mensalidade ficam no painel do capitão e não na página pública do clube. Nenhum pagamento ou envio de cobrança é realizado neste site demonstrativo.</p></section>
  <section><h2>3. Elenco e inteligência artificial</h2><p>Cada time deve ter no mínimo {liga.minimoJogadores} e no máximo {liga.maximoJogadores} jogadores inscritos. Cada jogador só pode representar um clube por vez.</p><p>O goleiro será controlado por inteligência artificial (IA) em todos os times. São permitidas até duas posições com IA em campo: o goleiro obrigatório e, se necessário, mais uma posição de linha.</p><p>Os elencos e as estatísticas desta demonstração são ilustrativos; a escalação com IA ainda não é simulada no site.</p></section>
  <section><h2>4. Plataformas e versões</h2><p>A primeira temporada será disputada nas versões de PS4 e Xbox One. No PS5, é necessário executar a versão de PS4 do jogo. No Xbox Series X|S, é necessário executar a versão de Xbox One. PC e as versões nativas de PS5 e Xbox Series X|S não participam.</p><p>O capitão deve informar a plataforma e a versão do jogo dos integrantes na pré-inscrição. Todos os integrantes devem utilizar uma das versões permitidas para a competição.</p></section>
  <section><h2>5. Premiação</h2><p>O campeonato terá premiação em dinheiro do 1º ao 5º colocado. As copas disputadas durante a temporada também terão premiação.</p><p>Valores, distribuição e condições das premiações serão divulgados pela organização antes do início.</p></section>
  <section><h2>6. Mercado e transferências</h2><p>Todos os times começam com o mesmo valor disponível para transferências. O valor inicial e as regras de utilização serão definidos pela organização.</p><p>Haverá janelas de mercado no início, no meio e no final da temporada. Movimentações devem respeitar essas janelas.</p><p>O mercado demonstrativo mostra jogadores sem clube. Não há saldo, propostas ou transações de transferências implementados nesta versão.</p></section>
  <section><h2>7. WO e expulsão</h2><p>O placar de uma partida decidida por WO é 1 × 0 para o adversário, com o gol atribuído a um jogador fictício. Ao acumular três WOs, o time é expulso do campeonato.</p><p>Tolerância de atraso, registro do WO, recursos e tratamento dos resultados após uma expulsão serão detalhados pela organização.</p></section>
  <section><h2>8. Súmulas e respeito</h2><p>As súmulas registram os resultados e as estatísticas das partidas. Na demonstração, apenas partidas encerradas entram na classificação.</p><p>Respeito a adversários, colegas e organização é condição de participação. Ofensas, discriminação e manipulação de resultados são incompatíveis com a liga. Procedimentos de contestação, suspensões e demais penalidades serão publicados antes da competição.</p></section>
  <section><h2>9. Organização e pré-inscrição</h2><p>A organização é conduzida por {liga.organizador}, amante de futebol, programação, empreendedorismo e jogos digitais.</p><p>Faça a pré-inscrição pelo WhatsApp {liga.contato}. Informe o nome do time, o capitão, a quantidade de jogadores, as plataformas e versões do jogo e a disponibilidade durante a semana.</p><p>O contato pelo WhatsApp não realiza cobrança nem conclui uma inscrição automaticamente.</p><a className="botao" href={liga.preInscricaoUrl} target="_blank" rel="noopener noreferrer">Pré-inscrição do time ↗</a></section>
</article>; }
